- .gitignore
- README.md
- WaterWizards.sln
- src/WaterWizard.Client/Program.cs
- src/WaterWizard.Client/WaterWizard.Client.csproj
- src/WaterWizard.Server/Program.cs
- src/WaterWizard.Server/WaterWizard.Server.csproj
- src/WaterWizard.Shared/Class1.cs
- src/WaterWizard.Shared/WaterWizard.Shared.csproj
- start-game.bat
- start-game.sh
This pull request introduces the initial setup for the "WaterWizards" project, a .NET 8-based battleship game featuring client-side graphics with Raylib-cs and networking with LiteNetLib. The key changes include project structure creation, client and server implementations, and setup scripts for running the game.
* Renamed the project from "MagicBattleShips" to "WaterWizards" and updated the `README.md` to reflect the new name, project structure, prerequisites, and setup instructions.
* Added a new Visual Studio solution file `WaterWizards.sln` that organizes the client, server, and shared projects.
* Created `src/WaterWizard.Client/Program.cs` with a basic game client using Raylib-cs for rendering a window with a welcome message.
* Added `WaterWizard.Client.csproj` with dependencies on …
> Infrastructure

- .github/workflows/nuke-build.yml
This pull request updates the `.github/workflows/nuke-build.yml` file to enhance security and add CodeQL analysis for the build process. The most important changes include granting specific permissions, initializing the .NET SDK for CodeQL, and adding a step to perform CodeQL analysis.
* Added `permissions` to the `build` job, granting `actions: read`, `contents: read`, and `security-events: write` to enhance security and control access.
* Added a step to initialize the .NET SDK using `github/codeql-action/init@v3` with `languages: 'csharp'`.
* Added a step to perform CodeQL analysis using `github/codeql-action/analyze@v3`.
> Static code analyzer

- WaterWizards.sln
- src/WaterWizard.Client/GameStateManager.cs
- src/WaterWizard.Client/NetworkManager.cs
- src/WaterWizard.Client/Program.cs
- src/WaterWizard.Server/Program.cs
- Updated project configuration in `WaterWizards.sln`.
- Implemented singleton pattern in `GameStateManager.cs` and added new game states, including `PreStartLobby`.
- Enhanced `NetworkManager.cs` to manage connected players, improve logging, and handle player connections/disconnections.
- Restructured main game loop in `Program.cs` for better initialization and error handling.
- Introduced a new `Player` class to encapsulate player data.
- Overall improvements to user experience and network communication.
> Enhance multiplayer functionality and state management

- src/WaterWizard.Client/GameStateManager.cs
- src/WaterWizard.Client/GameTimer.cs
This pull request introduces a `GameTimer` class to manage game timing and integrates it into the `GameStateManager` class. Additionally, it includes minor refactoring for improved readability and precision in UI-related code. Below are the most important changes grouped by theme:
* Added a new `GameTimer` class to handle game timing, including methods for updating, drawing, and resetting the timer. The timer tracks elapsed time and triggers actions when the time limit is reached. (`src/WaterWizard.Client/GameTimer.cs`)
* Integrated the `GameTimer` into `GameStateManager`, initializing it in the constructor and updating it in the `UpdateAndDraw` method to handle timeouts in the hosting menu. (`src/WaterWizard.Client/GameStateManager.cs`) …
> Game timer

- src/WaterWizard.Shared/Cards.cs
ich habe mal Julians Card Klasse genommen, sieht ganz gut aus
> Julians Cards Class 

- src/WaterWizard.Server/GameSessionTimer.cs
- src/WaterWizard.Server/Program.cs
https://github.com/users/maxk2807/projects/1/views/1?query=sort%3Aupdated-desc+is%3Aopen&pane=issue&itemId=108584975&issue=maxk2807%7CWaterWizards%7C69
> Add GameSessionTimer to manage game session timing and updates

- src/WaterWizard.Client/gamescreen/ActiveCards.cs
- src/WaterWizard.Client/gamescreen/GameHand.cs
- src/WaterWizard.Client/gamescreen/GameScreen.cs
> draw active cards field

- src/WaterWizard.Client/GameStateManager.cs
- src/WaterWizard.Client/NetworkManager.cs
- src/WaterWizard.Client/gamestates/ConnectingMenuState.cs
- src/WaterWizard.Client/gamestates/HostingMenuState.cs
- src/WaterWizard.Client/gamestates/IGameState.cs
- src/WaterWizard.Client/gamestates/InGameState.cs
- src/WaterWizard.Client/gamestates/LobbyListMenuState.cs
- src/WaterWizard.Client/gamestates/MainMenuState.cs
- src/WaterWizard.Client/gamestates/PlacementPhaseState.cs
- src/WaterWizard.Client/gamestates/PreStartLobbyState.cs
- src/WaterWizard.Server/Program.cs
- src/WaterWizard.Server/ServerGameStates/IServerGameState.cs
- src/WaterWizard.Server/ServerGameStates/InGameState.cs
- src/WaterWizard.Server/ServerGameStates/LobbyState.cs
- src/WaterWizard.Server/ServerGameStates/PlacementState.cs
- src/WaterWizard.Server/ServerGameStates/ServerGameStateManager.cs
Review Pls
- Implemented ConnectingMenuState for entering IP address and connecting to a server.
- Created HostingMenuState to display hosting information and player connection status.
- Added InGameState to manage game pause functionality and draw the game screen.
- Introduced LobbyListMenuState to display available lobbies and allow joining.
- Developed MainMenuState with animated title and buttons for joining or hosting a lobby.
- Implemented PlacementPhaseState for ship placement instructions.
- Added PreStartLobbyState to manage player readiness and start game functionality.
- Defined IGameState interface for consistent game state management.
> Add game state classes for connecting, hosting, and in-game menus

- src/WaterWizard.Client/NetworkManager.cs
- src/WaterWizard.Server/Program.cs
- src/WaterWizard.Server/ServerGameStates/IServerGameState.cs
- src/WaterWizard.Server/ServerGameStates/InGameState.cs
- src/WaterWizard.Server/ServerGameStates/LobbyState.cs
- src/WaterWizard.Server/ServerGameStates/PlacementState.cs
- src/WaterWizard.Server/ServerGameStates/ServerGameStateManager.cs
Bug fix: Player couldnt get ready anymore --> Bug Fixed working again: When all Player Ready up will get you into the ship placement state
> B150 hotfix server client ready

- src/WaterWizard.Client/NetworkManager.cs
- src/WaterWizard.Client/gamescreen/GameScreen.cs
- src/WaterWizard.Client/gamescreen/cards/ActiveCards.cs
- src/WaterWizard.Client/gamescreen/cards/CardStack.cs
- src/WaterWizard.Client/gamescreen/cards/CardStacksField.cs
- src/WaterWizard.Client/gamescreen/cards/GameCard.cs
- src/WaterWizard.Client/gamescreen/cards/GameHand.cs
- src/WaterWizard.Server/GameState.cs
- src/WaterWizard.Server/ServerGameStates/InGameState.cs
- src/WaterWizard.Server/ServerGameStates/PlacementState.cs
Nach PlacementPhase, also in GamePhase, click auf Kartenstapel links, um eine zufällige Karte dieses Stapels zu "kaufen" (noch kostenlos). Karte wird bei dir und beim Gegner angezeigt. Beim Gegner wird die Karte zu einer Deterministischen "Ersten" Karte, ohne zusammenhang zur echten gekauften Karte.
close #74
> F74 server karten verwaltung und "Kauf"

- src/WaterWizard.Client/NetworkManager.cs
- src/WaterWizard.Client/gamescreen/GameBoard.cs
- src/WaterWizard.Client/gamescreen/GameScreen.cs
- src/WaterWizard.Client/gamescreen/cards/ActiveCards.cs
- src/WaterWizard.Client/gamescreen/cards/CardStack.cs
- src/WaterWizard.Client/gamescreen/cards/CardStacksField.cs
- src/WaterWizard.Client/gamescreen/cards/GameCard.cs
- src/WaterWizard.Client/gamescreen/cards/GameHand.cs
- src/WaterWizard.Client/gamescreen/ships/DraggingShip.cs
- src/WaterWizard.Server/GameState.cs
- src/WaterWizard.Server/ServerGameStates/InGameState.cs
- src/WaterWizard.Server/ServerGameStates/PlacementState.cs
> F138 validate ship placement

- .github/codeql/codeql.yml
- .github/workflows/codeql-config.yml
This pull request removes a custom CodeQL configuration file. The deleted configuration included specific queries focused on security and code quality, filtering for errors and warnings with the "code-quality" tag.
* [`.github/codeql/codeql.yml`](diffhunk://#diff-3ea5384684ef9cec5901c8d311c71cafd1403c94c26031d87c05d52796040c6cL1-L8): Removed the "Custom CodeQL Configuration" section, which defined queries targeting security and code quality issues with severity levels of "error" and "warning."
> remove custom CodeQL configuration file

- src/WaterWizard.Client/NetworkManager.cs
- src/WaterWizard.Client/gamescreen/GameBoard.cs
- src/WaterWizard.Client/gamescreen/cards/GameCard.cs
- src/WaterWizard.Client/gamescreen/cards/GameHand.cs
- src/WaterWizard.Server/CardAbilities.cs
- src/WaterWizard.Server/GameState.cs
- src/WaterWizard.Server/ServerGameStates/InGameState.cs
- src/WaterWizard.Shared/CardStats.cs
- src/WaterWizard.Shared/CardTarget.cs
- src/WaterWizard.Shared/CardVariant.cs
- src/WaterWizard.Shared/Cards.cs
lays some foundations for the implementation of cards on the server + does some ui for card casting
closes #182
> F182 client default attack

- src/WaterWizard.Server/Card/FireboltCard.cs
- src/WaterWizard.Server/CardAbilities.cs
- src/WaterWizard.Server/GameState.cs
- src/WaterWizard.Server/ServerGameStates/InGameState.cs
- src/WaterWizard.Server/ServerGameStates/PlacementState.cs
- src/WaterWizard.Server/handler/ShipHandler.cs
This pull request refactors the handling of ship-related operations in the `WaterWizard.Server` project by introducing a centralized `ShipHandler` class. It removes redundant methods from `GameState` and updates references across multiple files to utilize the new handler. Additionally, it improves code readability and simplifies logic in several areas.
* **Centralized Ship Management**: Introduced `ShipHandler` to manage ship-related operations, replacing methods like `GetShips`, `AddShip`, `AreAllShipsDestroyed`, and `SendShipReveal` that were previously part of the `GameState` class. This improves modularity and separation of concerns. (`[[1]](diffhunk://#diff-1c777249b2a574d09885c5808a01c43117ec19a0ce233266cdfe31c1a4ecb5baL44-R44)`, …
> F244 refactor game state.cs server

- src/WaterWizard.Client/gamescreen/GameBoard.cs
- src/WaterWizard.Client/gamescreen/cards/CastingUI.cs
- src/WaterWizard.Client/network/ClientService.cs
- src/WaterWizard.Server/CardAbilities.cs
- src/WaterWizard.Server/GameState.cs
- src/WaterWizard.Server/PlacedShip.cs
- src/WaterWizard.Server/handler/CardHandler.cs
- src/WaterWizard.Server/handler/CellHandler.cs
- src/WaterWizard.Server/handler/ShipHandler.cs
- start-clients.bat
> F102 card heal

- src/WaterWizard.Client/gamescreen/GameBoard.cs
- src/WaterWizard.Client/gamescreen/cards/CastingUI.cs
- src/WaterWizard.Client/network/ClientService.cs
- src/WaterWizard.Server/CardAbilities.cs
> F270 casting UI allied ships

- src/WaterWizard.Client/gamescreen/RessourceField.cs
- src/WaterWizard.Client/gamescreen/handler/HandleRessources.cs
- src/WaterWizard.Client/network/ClientService.cs
- src/WaterWizard.Server/Card/DamageCardFactory.cs
- src/WaterWizard.Server/Card/FrostBoltCard.cs
- src/WaterWizard.Server/GameState.cs
- src/WaterWizard.Server/ServerGameStates/InGameState.cs
- src/WaterWizard.Server/handler/GoldHandler.cs
This pull request introduces a new "gold freeze" mechanic to the game, implemented through a new `FrostBoltCard` and supporting changes across the client and server. The mechanic temporarily disables gold generation for a player when their ship is hit by the FrostBolt. Key changes include updates to the game state, new handlers for the gold freeze effect, and client-server communication enhancements.
* Added `FrostBoltCard` with functionality to deal damage and freeze gold generation for 8 seconds when hitting a ship (`src/WaterWizard.Server/Card/FrostBoltCard.cs`).
* Updated `DamageCardFactory` to include the new `FrostBoltCard` as a valid card variant (`src/WaterWizard.Server/Card/DamageCardFactory.cs`).
* Introduced gold freeze timers and methods in `GameState` to manage and broadcast …
> Add gold freeze mechanics and update handling in game state and client

- src/WaterWizard.Client/gamescreen/cards/CastingUI.cs
> F296 click again confirm casting for Battlefield casting

- src/WaterWizard.Client/gamescreen/GameScreen.cs
- src/WaterWizard.Client/gamescreen/RessourceField.cs
- src/WaterWizard.Server/ServerGameStates/InGameState.cs
- src/WaterWizard.Server/handler/CardHandler.cs
> B358 cant buy cards

- src/WaterWizard.Client/gamescreen/cards/CastingUI.cs
- src/WaterWizard.Client/gamescreen/cards/GameHand.cs
- src/WaterWizard.Client/gamescreen/handler/HandleCards.cs
- src/WaterWizard.Client/network/ClientService.cs
- src/WaterWizard.Server/handler/CardHandler.cs
- src/WaterWizard.Server/handler/ManaHandler.cs
> Cards Dissappear bug

- src/WaterWizard.Server/GameState.cs
- src/WaterWizard.Server/ServerGameStates/InGameState.cs
- src/WaterWizard.Server/handler/GoldHandler.cs
- src/WaterWizard.Server/handler/ManaHandler.cs
- src/WaterWizard.Shared/Gold.cs
- src/WaterWizard.Shared/Mana.cs
- src/WaterWizardTests/GoldTest.cs
This pull request removes outdated documentation files and consolidates launcher-related instructions into the main `README.md`. The most notable changes include the deletion of changelog and commit convention templates, the removal of a standalone game launcher README, and the integration of launcher usage and troubleshooting instructions into the `README.md`.
* Removed `CHANGELOG.md` and `CHANGELOG_TEMPLATE.md` as they are no longer maintained. [[1]](diffhunk://#diff-06572a96a58dc510037d5efa622f9bec8519bc1beab13c9f251e97e657a9d4edL1-L105) [[2]](diffhunk://#diff-455e755627c7c04a0b356066eee5c1da52f2d286ee59dd517cae7c00b8bd9671L1-L61)
* Deleted `COMMIT_CONVENTIONS.md` to streamline documentation.
* Removed `GAME_LAUNCHER_README.md`, consolidating its content into the main `README.md`.
* …
> F391 mana gold raise

- src/WaterWizard.Server/CardAbilities.cs
- src/WaterWizard.Server/handler/CardHandler.cs
Alle Karten funktionieren wieder.
Eventuell werden die Karten nicht zu den Aktiven Karten Rechts hinzugefügt
> Revert to HandleAbility instead of HandleAbilityWithHandlers

- src/WaterWizard.Client/gamescreen/GameScreen.cs
- src/WaterWizard.Client/gamescreen/handler/HandleShips.cs
- src/WaterWizard.Server/Card/damage/ArcaneMissileCard.cs
- src/WaterWizard.Server/Card/damage/FirballCard.cs
- src/WaterWizard.Server/Card/damage/FireboltCard.cs
- src/WaterWizard.Server/Card/damage/FrostBoltCard.cs
- src/WaterWizard.Server/Card/damage/GreedHitCard.cs
- src/WaterWizard.Server/Card/damage/LifeStealCard.cs
- src/WaterWizard.Server/Card/damage/MagicAttackCard.cs
- src/WaterWizard.Server/Card/environment/ThunderCard.cs
- src/WaterWizard.Server/Card/utility/HoveringEyeCard.cs
- src/WaterWizard.Server/ServerGameStates/InGameState.cs
- src/WaterWizard.Server/handler/AttackHandler.cs
- src/WaterWizard.Server/handler/CardHandler.cs
- src/WaterWizard.Server/handler/CellHandler.cs
- src/WaterWizard.Server/handler/CoordinateTransform.cs
- src/WaterWizard.Server/handler/ShipHandler.cs
bug fixed ships now appear like on a real board
> B215 wrong enemy ship placement
